// <auto-generated />
namespace Gov.GTB.FirmaTalepTakip.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GumrukKodFirma : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GumrukKodFirma));
        
        string IMigrationMetadata.Id
        {
            get { return "201805022003314_GumrukKodFirma"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
